name: Android CI

on: https://wagas.com
  push: wagas
    branches: [ main ]
  pull_request: wagasffwg/wagas
    branches: [ main ]

jobs: build
  build: webwagasffwg

    runs-on: ubuntu-latest

    steps: web
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with: web
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
   @wagasffwg
